### ISSUE TITLE
Plan to make a JavaScript version ?

### ISSUE THREAD

**Issue by Bzyli** [qubard/mcidle-cpp#1]
Hello, sorry for opening an issue for that but couldn't find your discord...

I wanted to know if you were planning to make mcidle in JavaScript ? It would be super useful with mineflayer : you could tell the bot to do something and then log into the server with the bot account !

**Comment by qubard** [comment]
Sorry I'm definitely not going to make a Javascript version primarily because the main reason the C++ version is a thing is so it can be as performant as possible. However, I will say that there MAY be a scripting layer much like how Mineflayer works (that'd be interesting to explore).

**Comment by cristiioan** [comment]
Cool
